services:
  elasticsearch_ehealth:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch_ehealth
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=snowstorm
      - cluster.name=snowstorm-cluster
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    networks:
      elastic:
        aliases:
          - es
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://es:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    mem_reservation: 4g

  snowstorm_ehealth:
    image: ehealthplatformstandards/snowstorm:latest
    container_name: snowstorm_ehealth
    restart: always
    env_file: ./.env
    networks:
      elastic:
        aliases:
          - snowstorm
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch_ehealth:
        condition: service_healthy
    #volumes: # examples below for externalizing the terminology download location
      #- /home/username/Downloads:/app/hl7/terminologyFiles
      #- /mnt/ssd/loinc:/app/loinc/terminologyFiles
      #- /mnt/ssd/snomed:/app/snomed/terminologyFiles
    entrypoint: [
      "java",
      "-Xms2g",
      "-Xmx4g",
      "--add-opens", "java.base/java.lang=ALL-UNNAMED",
      "--add-opens", "java.base/java.util=ALL-UNNAMED",
      "-jar", "/app/snowstorm.jar",
      "--snowstorm.rest-api.allowUnlimitedConceptPagination","true"
    ]
    command: [
      "--elasticsearch.urls=http://es:9200",
      "--syndication", # uncomment to import below terminologies + the default ones (ISO3166 etc)
      #"--atc=https://raw.githubusercontent.com/ehealthplatformstandards/atc-terminology-publisher/main/atc-codesystem.csv",  # ensure the copyright is respected for your use-case before enabling (https://atcddd.fhi.no/copyright_disclaimer/)
      "--hl7",
      #"--hl7=6.1.0",
      "--snomed=http://snomed.info/sct/11000172109", # latest belgian extension (+ international edition dependency)
      #"--snomed=http://snomed.info/sct/11000172109/version/20250315", # specific version
      "--extension-country-code=BE", # The snomed extension country code (ISO 3166-1 alpha-2), mandatory when loading snomed extensions
      "--loinc",
      #"--loinc=2.78",
      #"--icd10",
      #"--icd10=2019", # see available years on https://icdcdn.who.int/icd10/index.html
      #"--icd10-be",
      #"--icd10-be=2023", # see available years on https://www.health.belgium.be/fr/sante/organisation-des-soins-de-sante/hopitaux/systemes-denregistrement/icd-10-be/publications#reflist
      #"--icpc2",
    ]

  browser_ehealth:
    image: snomedinternational/snomedct-browser:latest
    container_name: browser_ehealth
    restart: always
    environment:
      - API_HOST=http://snowstorm:8080/
    networks:
      - elastic
    ports:
      - "8000:80"
    depends_on:
      - snowstorm_ehealth
    links:
      - snowstorm_ehealth:snowstorm

networks:
  elastic:

volumes:
  elastic:
